SyneRBI/SIRF-SuperBuild

- SuperBuild.cmake
- SuperBuild/External_SIRF.cmake
WARNING: This breaks backwards compatibility.
Matlab_ROOT_DIR is the variable used by CMake's FindMatlab.cmake so is what we should use as well.
Currently we use this to set both variables for SIRF (as SIRF 0.9.0 used MATLAB_ROOT).
> Use Matlab_ROOT_DIR as opposed to MATLAB_ROOT

- SuperBuild/External_HDF5.cmake
- version_config.cmake
updates necessary for Windows, but beneficial for other systems
> HDF5 fixes

- SuperBuild.cmake
Remove `EXTERNAL_PROJECT_BUILD_TYPE` from CMake GUI and make it equal to the value of `CMAKE_BUILD_TYPE`. #49.
> Align EXTERNAL_PROJECT_BUILD_TYPE with CMAKE_BUILD_TYPE

- SuperBuild/External_Gadgetron.cmake
- version_config.cmake
Set `DEVEL_BUILD` as an advanced variable. 
Changed `BUILD_GADGETRON_NATIVE_PYTHON_SUPPORT` from `option` to `set`.
> DEVEL_BUILD and BUILD_GADGETRON_NATIVE_PYTHON_SUPPORT

- .travis.yml
- SuperBuild.cmake
Get OSX to compile on Travis.
- Use absolute paths
- Give full paths to python executable, library and include directory for either python2 or python3.\
- Upgrade to boost 1.66
> Travis OSX

- SuperBuild.cmake
- SuperBuild/External_glog.cmake
- SuperBuild/External_petmr_rd_tools.cmake
- version_config.cmake
Will build [UCL/petmr-rd-tools](https://github.com/UCL/petmr-rd-tools) if requested. Not that both `ITK` and [glog](https://github.com/google/glog) are required to successfully build. I have left them out of the dependency list in `External_petmr_rd_tools.cmake`. Once happy, we should add this to the VM.
> Add option to build UCL/petmr-rd-tools

- CHANGES.md
- SuperBuild.cmake
- SuperBuild/External_SIRF.cmake
most of this (see original description below) is migrated to https://github.com/CCPPETMR/SIRF/pull/163
+ [x] use `PYTHON_STRATEGY` (`CONDA|SETUP_PY|PYTHONPATH)`
+ [x] example: `cmake -DSIRF_TAG=setup_py -DPYTHON_STRATEGY=SETUP_PY`
+ [x] provides `sirf`
+ [x] alias `p(Gadgetron|STIR|Utilities)` to `sirf.p(Gadgetron|STIR|Utilities)` for backward-compatibility
- `INSTALL/`
+ `python/`
* `*.(py|so)`
- `INSTALL/`
+ `python/`
* `setup.py`
* `sirf/`
- `__init__.py`
- `*.(py|so)`
* `p*/__init__.py`
+ https://stackoverflow.com/a/48015772/3896283
+ won't need to re-implement `cmake` call in `conda`
+ will need to pass `cmake` build args to `setup.py` (pretty easy)
> expose python strategy

- .travis.yml
brew now needs `brew upgrade python` to get python3. We also change the way we find the python executable.
Closes #97
> fix Travis for OSX Python3

- SuperBuild/External_glog.cmake
I haven't properly tested this as I haven't been able to use the superbuild, but I forgot to push this a few months ago when I found it.
> Glog previously used STIR version tag instead of its own.

- SuperBuild/External_ACE.cmake
- version_config.cmake
Reflects updates done on ACE.
Uses Gadgetron version that compiles with GPU support.
> Update ACE package

- SuperBuild/External_ITK.cmake
By default, ITK builds its own HDF5. This shouldn't create conflicts, but might do.
We should be fine with using our own.
> Let ITK use the same HDF5 as we do

- .travis.yml
- SuperBuild/External_Boost_buildboost.cmake
- SuperBuild/External_Boost_configureboost.cmake
- version_config.cmake
ISMRMRD searches for unit_test. As we don't build it, it might find a system version, which would then create conflicts between boost versions (as in #165)
> Also build the boost unit_test framework and other fixes

- .travis.yml
> Travis should turn red when unit tests fail

- SuperBuild.cmake
- SuperBuild/External_Boost.cmake
> If building own version of boost, try to minimise looking for other versions

- .travis.yml
- OSX builds had a weird time-out at the end of all the testing when doing `cat` of the log files, the Travis log file contained only the first part of (usually) the gadgetron.log and then a time-out message that 10mins went past without output. As this doesn't happen in the SIRF Travis build, the only explanation that I can see is some strange limitation of the subshell feature of OSX. This PR therefore only writes log files when something went wrong.
- Disabled docker builds for now, pending fixes #195 
- Also synced with (most of) the SIRF .travis.yml.
> Travis changes for OSX and docker

- .travis.yml
- docker/Dockerfile
- docker/build_essential-ubuntu.sh
- docker/build_gadgetron-ubuntu.sh
- docker/build_system-ubuntu.sh
- docker/devel/test.sh
- docker/docker-compose.yml
- docker/user_python-ubuntu.sh
- docker/user_sirf-ubuntu.sh
> fix docker & ccache

- version_config.cmake
This allows building SIRF on Ubuntu 16.04 with `USE_SYSTEM_BOOST=ON` when not building Gadgetron
> reduce Boost version requirement when not building Gadgetron

- SuperBuild/External_Gadgetron.cmake
- SuperBuild/External_ITK.cmake
- SuperBuild/External_SIRF.cmake
- SuperBuild/External_STIR.cmake
This way, we don't really need the verbose flags anymore.
> Use --output-on-failure for ctest commands

- .travis.yml
As of boost 1.69, boost.Process is broken. https://stackoverflow.com/a/54912043
To fix, remove :: from all occurences of ::sigtimedwait, ::sigaddset and ::sigemptyset
> try to fix travis osx boost1.69/gadgetron

- CHANGES.md
- version_config.cmake
Now that `NIFTYREGConfig.cmake` is case sensitive (https://github.com/KCL-BMEIS/niftyreg/pull/53), switch remote back from rijobro fork to KCL fork.
> update NiftyReg version for case-sensitive systems

- .travis.yml
- version_config.cmake
This should fix the build failing because the `finite_diff_for_sirf` branch has been deleted in `CCPi-Framework`
> change the CCPi-Framework branch

- SuperBuild.cmake
- SuperBuild/External_SIRF-Contribs.cmake
- version_config.cmake
use with e.g., `from sirf.contrib.kcl import Prior`
fixes #263
> clone and install sirf-contrib

- docker/README.md
long overdue update to docker readme. Should fully replace the [wiki](https://github.com/CCPPETMR/SIRF/wiki/SIRF-SuperBuild-on-Docker) (which already redirects to this readme)
> Docker docs

- CHANGES.md
- CMake/SetCanonicalDirectoryNames.cmake
- README.md
- SuperBuild.cmake
- SuperBuild/External_ACE.cmake
- SuperBuild/External_Armadillo.cmake
- SuperBuild/External_FFTW3.cmake
- SuperBuild/External_FFTW3double.cmake
- SuperBuild/External_GTest.cmake
- SuperBuild/External_Gadgetron.cmake
- SuperBuild/External_HDF5.cmake
- SuperBuild/External_ISMRMRD.cmake
- SuperBuild/External_ITK.cmake
- SuperBuild/External_NIFTYPET.cmake
- SuperBuild/External_SIRF.cmake
- SuperBuild/External_STIR.cmake
- SuperBuild/External_SWIG.cmake
- SuperBuild/External_glog.cmake
- SuperBuild/External_pet_rd_tools.cmake
- SuperBuild/External_siemens_to_ismrmrd.cmake
- env_ccppetmr.csh.in
- env_ccppetmr.sh.in
- introduce a new macro SetCanonicalDirectoryNames to replace lots of things related to directory names
- make ${proj}_SOURCE_DIR a cached variable such that it can be set
- rename ${proj}_Install_dir to ${proj}_INSTALL_DIR for consistency
Closes #324
> make proj_SOURCE_DIR cached and reduce repetition for DIR variables

- SuperBuild/External_Armadillo.cmake
Gadgetron probably doesn't need Armadillo's capability to save/load HDF5 files. Disabling it reduces interdependencies.
Closes #354
> compile Armadillo without HDF5 support

- .travis.yml
`brew` can change versions on packages due to dependencies etc. So we need to find the BLAS version
just before starting to build.
Fixes #356
> [TRAVIS] OSX: find latest openblas version

- SuperBuild/External_FFTW3.cmake
- SuperBuild/External_SWIG.cmake
> use canonical dir names in swig and fftw for win32

- .travis.yml
- version_config.cmake
closes #304 by removing CIL repos from the `DEVEL_BUILD`. This is due to backward incompatibility of the structure of the CIL package from version 19.10 on.
> Cil devel build tag

- .travis.yml
- TODO (later in a different PR if needed): ideally should really build docker using current SuperBuild commit
(instead of `-b master` in `docker/user_sirf-ubuntu.sh`) https://github.com/SyneRBI/SIRF-SuperBuild/pull/361#issuecomment-601102294
- fixes #332
- maybe fixes #398 (seems duplicate)?
> skip docker on PRs/non-master branches

- CHANGES.md
- SuperBuild/External_HDF5.cmake
... if it's defined and `USE_SYSTEM_HDF5=ON`
> Pass HDF5_ROOT through to projects

- SuperBuild/External_STIR.cmake
By default, disable STIR's HDF5 support. Avoids this current problem - https://github.com/SyneRBI/SIRF/issues/685.
> disable STIR HDF5 support by default

- SuperBuild/External_STIR.cmake
- add `${HDF5_CMAKE_ARGS}`
- move `${Boost_CMAKE_ARGS}` to the same place for consistency
Fixes #421
> Update External_STIR.cmake for HDF5

- SuperBuild/External_Boost.cmake
We get linking problems with boost system if the C++ versions don't match (i.e. the one used to compile boost, and the current one), specifically with boost::system::detail::generic_category_instance
Setting this variable forces Boost to use an inline variable, as opposed to the instantiated variable in the library
Fixes https://github.com/SyneRBI/SIRF-SuperBuild/issues/161
> set preprocessor define BOOST_ERROR_CODE_HEADER_ONLY

- SuperBuild/External_Armadillo.cmake
This override the GNUinstallation conventions, as none of the other packages uses this.
Fixes #430
> force Armadillo libraries to be installed in lib

- .travis.yml
Use the simpler mechanism introduced in SIRF earlier and which seems to work fine there.
Take the opportunity to sync parts of the comments with the SIRF .travis.yml
> [TRAVIS] change setting of PY_EXE on OSX, and use only python3

- SuperBuild/External_STIR.cmake
STIR v4.* has extra functionality for CTAC->mu if this library is available. We enable this now by default.
Also fix use of a related CMake variable (we were using `STIR_USE_JSON` while the option is `STIR_DISABLE_JSON`)
> Let STIR depend on nlohmann_json by default and fix

- SuperBuild/External_FFTW3.cmake
On Windows:
- run lib to create export libraries
- set FFTW3_CMAKE_ARGS correctly
Other systems:
- correct location of include files in FFTW3_CMAKE_ARGS
> improvements when building FFTW (mostly Windows)

- CHANGES.md
- SuperBuild/External_JSON.cmake
- version_config.cmake
In most cases, we don't need to build the tests, so make it an option BUILD_TESTING_JSON
> set JSON to 3.9.1 and don't build tests by defaults

- version_config.cmake
With Visual Studio, ISMRMRD utiliites have double-linking problems with boost program_options.
We therefore set the ISMRMRD version to a branch corresponding to
https://github.com/ismrmrd/ismrmrd/pull/134.
This branch is currently synced with 1.4.1 + one update. Ideally ISMRMRD merges the PR.
Fixes #403
> work-around ISMRMRD compilation problem with Visual Studio

- .travis.yml
This removes Python 2.7 support from travis.
VM: https://github.com/SyneRBI/SyneRBI_VM/pull/170
> removes py27 builds in travis

- CHANGES.md
- SuperBuild/External_ITK.cmake
- docker/user_service-ubuntu.sh
we don't need this module for STIR/SIRF.
Not building it increases chances of success with long paths on Windows
> do not build ITK_ReviewModule by default

- CHANGES.md
- README.md
- SuperBuild/External_Gadgetron.cmake
- patches/Gadgetron_include-patch.py
- patches/cil-patch.py
Applies a patch to the installed Gadgetron include file `hoNFFT.h` that creates a compiler error in @johannesmayer [RPE-encoding](https://github.com/johannesmayer/SIRF/tree/rpe-encoding) branch.
> Patch Gadgetron include files for RPE encoding

- CHANGES.md
- version_config.cmake
added ACE, astra-toolbox and CCPi-Astra do advanced options
Removed CCPi-FrameworkPlugins that is merged into CCPi-Framework since v20.11
> Add external projects to mark as advanced

- .travis.yml
Because... who needs stable tagged releases?
Also really should just use GHA for this rather than Travis.
> push more docker builds

- .github/workflows/c-cpp.yml
- SuperBuild/External_CCPi-Framework.cmake
- docker/requirements.txt
- version_config.cmake
updates to latest CIL release [21.0.0](https://github.com/vais-ral/CCPi-Framework/releases/tag/v21.0.0)
> Bump cil tag

- docker/docker-compose.yml
- docker/sirf-compose
`docker-compose.yml` used the special variabled `UID` and `GROUPS`, but it seems impossible to get `GROUPS` to be exported. Therefore, I switched to using non-special env variables, but set those explicitly in `sirf-compose`.
Fixes #464
> docker: fix UID/GID on Linux

- SuperBuild/External_HDF5.cmake
- version_config.cmake
This shouldn't change the actual versions checked out, but allows the user to change the HDF5_TAG as for other projects. It also prevents us to have to take care of mdf5 sums.
Best to merge once 3.0 is out.
> use git clone for HDF5

- .travis.yml
- docker/.dockerignore
It is supposed to *not* ignore devel/.ccache, but it did. Apparently this was caused by an initial /.
Fixes #534
> fix .dockerignore

- CHANGES.md
- SuperBuild.cmake
PR #550 disabled NiftyPET only for docker builds, however, since `NiftyPET` requires Python 2 and we dropped support for Python2 NiftyPET should just be disabled throughout and enabled by a daring user.
> disable NiftyPET by default as it requires python2

- version_config.cmake
Currently used ISMRMRD 1.4.1 does not correctly generate undersampled raw data (no calibration area present).
This PR tries to shift to ISMRMRD 1.4.2.
> Try ISMRMRD 1.4.2

- docker/.bashrc
- docker/.profile
- docker/build_system-ubuntu.sh
- docker/entrypoint.sh
- docker/user_sirf-ubuntu.sh
see commit messages if what this does.
@paskino, could you have a quick look?
> Docker small fixes

- .travis.yml
- CHANGES.md
- docker/DocForDevelopers.md
- docker/Dockerfile
- docker/README.md
- docker/entrypoint.sh
- docker/service.sh
At least on some systems, changing ownership of /opt/* took a long time when the container was created. Instead, we just give everyone write permissions, but do this when creating the images.
Fixes #555
> docker: no longer chown /opt

- version_config.cmake
update CIL to latest versions pre-training. This is likely to change and the repos are going to be tagged properly, but it's for testing.
> bump CIL tags

- SuperBuild/External_astra-toolbox.cmake
Removes the temporary `python_build` and `python_install` files from the `astra-toolbox` source code.
closes https://github.com/SyneRBI/SyneRBI_VM/issues/187
> remove temporary build files from source

- CHANGES.md
- docker/entrypoint.sh
The entrypoint.sh failed if `GROUP_ID` refers to an existing group, as the `adduser` command referred to it via the wrong name.
Fixes #606
> docker: create user with gid

- docker/entrypoint.sh
Use numerical numbers for UID:GID for the chown command in entrypoint.sh
Fixes #609
> docker: another fix for user with existing group

- CHANGES.md
- SuperBuild/External_Boost.cmake
- when USE_SYSTEM_BOOST=OFF, set Boost_NO_SYSTEM_PATHS=ON to increase our chances of finding our own version
- when USE_SYSTEM_BOOST=OFF, pass BOOSTROOT and Boost_DIR to projects (when set)
Fixes #627
> fix corner cases for Boost

- CHANGES.md
- version_config.cmake
- `DEVEL_BUILD` was on `origin/master`, causing problems as it is too recent compared to ISMRMRD 1.5.0.
- default build was a fairly old version, likely causing problems with ISMRMRD 1.5.0.
> fix siemens_to_ismrmrd to 6d0ab3d3d0c8ade5c0526db1c6af9825008425ad

- CHANGES.md
- version_config.cmake
update the version of CIL to the latest (today's) tagged version.
> set CIL version to 21.4.0

- CHANGES.md
- SuperBuild/External_Boost_buildboost.cmake
Adds `regex` and `random` to Windows Boost build, but they are not responsible for the issue #720
> Add Boost regex and random for Windows build

- VirtualBox/scripts/update_VM.sh
The script `update_VM.sh` refers to the archived repo https://github.com/SyneRBI/SyneRBI_VM 
https://github.com/SyneRBI/SIRF-SuperBuild/blob/775d4a18bccc0bc67b194622eb976acd61620a8f/VirtualBox/scripts/update_VM.sh#L4-L6
I updated the location of the `UPDATE.sh` script.
> [ci skip] updates the path in the update_VM.sh script

- CHANGES.md
- SuperBuild/External_astra-python-wrapper.cmake
- SuperBuild/External_astra-toolbox.cmake
closes #743 
- Removes files that may be present in the source directory by `cmake -E rm -f`. 
- Removes temporary scripts from where they have been created after they have been copied to the right destination.
> Fix astra update

- CHANGES.md
- docker/requirements.txt
- docker/requirements_conda_forge.txt
- version_config.cmake
CIL-ASTRA has been merged (and patched) into CIL code (after a lengthy relicensing procedure), so now, the SuperBuild installs CIL-ASTRA master (not patched) on top of the correct master CIL code, resulting in the [error](https://github.com/SyneRBI/SIRF-SuperBuild/runs/7601445525?check_suite_focus=true).
> Set CIL version to commit before CIL-ASTRA merge

- CHANGES.md
- CMake/FindCython.cmake
- VirtualBox/scripts/INSTALL_prerequisites_with_apt-get.sh
- VirtualBox/scripts/INSTALL_python_packages.sh
- VirtualBox/scripts/UPDATE.sh
- VirtualBox/scripts/bootstrap_ubuntu.sh
- docker/build_essential-ubuntu.sh
- docker/requirements.txt
Creates the VM from the docker files.
Installs custom pip. 
closes #742
> Fixes for VirtualBox

- docker/build_system-ubuntu.sh
This allows building ROOT if a user would want to (or we ourselves in the future)
Fixes #728
> [docker/VM]: add uuid-dev apt package

- CHANGES.md
- version_config.cmake
> Use GTest 1.12.1 and glog 0.6.0

- .github/workflows/c-cpp.yml
- docker/build_system-ubuntu.sh
- version_config.cmake
On GHA, libunwind-14 is installed, but that creates trouble for other packages.
Fixes https://github.com/SyneRBI/SIRF/issues/1155
> fix GHA problems on Ubuntu 22.04

- docker/user_python-ubuntu.sh
Apparently the new miniconda installer asks for 3 inputs. 
closes #806
> add no to conda install

- SuperBuild.cmake
- SuperBuild/External_Gadgetron.cmake
- SuperBuild/External_ISMRMRD.cmake
- SuperBuild/External_pugixml.cmake
- VirtualBox/scripts/INSTALL_prerequisites_with_apt-get.sh
- version_config.cmake
ISMRMRD needs pugixml these days, and my CentOS system doesn't have it.
I also updated Boost requirements as ISMRMRD failed to compile with boost 1.68.0
> Pugixml for ISMRMD and other small fixes

- docker/user_service-ubuntu.sh
Uses environment.yml from SIRF-Exercises if using conda, and it is found. Defaults to requirements.txt if not found or not using conda.
closes #814
> use environment.yml from SIRF-Exercise

- docker/requirements.yml
- docker/user_python-ubuntu.sh
- fix mamba install (fixes #826)
- suppress missing `pip` dependency warning
https://github.com/bird-house/finch/pull/245 didn't work, but [rtfd](https://mamba.readthedocs.io/en/latest/mamba-installation.html) did :)
> docker: fix `mamba` install

- CHANGES.md
- SuperBuild.cmake
SIRF Matlab support is out-of-date and could generate conflicts with Python shared libraries.
Equivalent of https://github.com/SyneRBI/SIRF/pull/1206. Could merge in 3.5 but also keep it for later.
> [CMAKE] default DISABLE_MATLAB to ON

- docker/requirements.yml
> remove obsolete version restriction for SciPy

- CHANGES.md
- SuperBuild/External_CCPi-Regularisation-Toolkit.cmake
- version_config.cmake
afaik the plan is:
- merge this PR
- tag & release SIRF v3.5.0 (https://github.com/SyneRBI/SIRF/issues/1198)
- fix #838 (in SIRF)
- tag & release SIRF >=3.5.1
> Bump CIL v23.1.0

- .github/workflows/docker_build.yml
- .github/workflows/test_cil.sh
- CHANGES.md
- SuperBuild/External_CIL.cmake
- docker/Dockerfile
- docker/service.sh
- version_config.cmake
- follow-up to #837
- fixes https://github.com/SyneRBI/SIRF-SuperBuild/pull/835#issuecomment-1709896466
- part of #836
- is a dependency of https://github.com/SyneRBI/SIRF/issues/1198
- fixes #827
diff: https://github.com/SyneRBI/SIRF-SuperBuild/pull/838/files?w=1
> CI: test docker CIL

- .github/workflows/c-cpp.yml
- .github/workflows/docker_build.yml
- .travis.yml
- docker/README.md
Apparently needed as Travis is running on Uuntu 20.04
Fixes #847
> Update .travis.yml to set DOCKER_BUILDKIT=1

- SuperBuild/External_Gadgetron.cmake
Adds an explicit check of CMake version and `message(FATAL_ERROR)` if CMake version is below 3.23.
Closes #823
> Add explicit CMake version check in case of Gadgetron testing ON

- CHANGES.md
- SuperBuild/External_SIRF.cmake
- SuperBuild/External_STIR.cmake
- version_config.cmake
STIR 6.0 (will) put `STIRConfig.cmake` to `lib/cmake/STIR-6.0`. https://github.com/UCL/STIR/pull/1358
Fixes #853 
This PR might fail in `DEVEL_BUILD=ON` until the STIR PR is merged.
> Stir 6 prep

- VirtualBox/scripts/INSTALL_CMake.sh
I use this script in other places as well, and it's convenient to be able to specify the CMake version. It also prevents a failure if the location doesn't exist yet. Finally, more quotes means less Codacy issues.
However, we don't test this (until VM creation stage), but it does work.
Not urgent to merge, but a nice to have.
> minor changes in VirtualBox to allow manual specification of CMake version

- CHANGES.md
- SuperBuild/External_STIR.cmake
It's nice to be able to use STIR Python for things that are not in `stir.STIR`, such as examining/manipulating projection data headers.
This PR increases build time a bit, but is otherwise harmless. Would need addition to `CHANGES.md`.
Any objections?
> default STIR_BUILD_SWIG_PYTHON=ON

- CHANGES.md
- version_config.cmake
> update to ROOT v6-28-12

- .github/workflows/test_cil.sh
- SuperBuild/External_CIL.cmake
Now that https://github.com/SyneRBI/SIRF/issues/1212 is fixed, we can reenable relevant tests
Reverts https://github.com/SyneRBI/SIRF-SuperBuild/pull/838/commits/160d5e5ac8396efb29322fe354083a7e5b5d8ad8
> re-enable some CIL tests depending on SIRF allocate()

- docker/build_gadgetron-ubuntu.sh
We have gcc-11 already
Fixes #883
> no longer install gcc-9 on docker/VM

- .github/workflows/docker.yml
Was already undocumented.
Really only existed for debugging purposes.
No longer required after https://github.com/SyneRBI/SIRF-Exercises/pull/221
> docker: drop `:jupyter` tag alias

- CHANGES.md
- docker/requirements.yml
- version_config.cmake
See https://github.com/gschramm/parallelproj/issues/69
> update parallelproj to 1.9.0 (and require it), as well as CIL, SIRF, STIR

- docker/docker-compose.gpu.yml
For e.g. parallelproj build.
It adds bloat to runtime, but is ok as a quickfix for now.
> docker: include CUDA toolkit

- CHANGES.md
- Dockerfile
- docker/requirements.yml
- docker/user_demos.sh
- version_config.cmake
Updates CIL to latest 
- [release v24.1.0 ](https://github.com/TomographicImaging/CIL/releases/tag/v24.1.0)
- Updates the anaconda.org `intel` channel to the new self hosted https://software.repos.intel.com/python/conda
> Update CIL tag to v24.1.0

- version_config.cmake
Updates the CIL version to a commit where all the stochastic estiomators (functions) developed during the stochastic hackathon have been merged:
- SGD ([v24.0.0](https://github.com/TomographicImaging/CIL/releases/tag/v24.0.0))
- SAG/SAGA https://github.com/TomographicImaging/CIL/pull/1624
- SVRG/LSVRG https://github.com/TomographicImaging/CIL/pull/1625
> bump CIL version to one with SAG/SAGA SVRG/LSVRG
