SyneRBI/SIRF-SuperBuild

SuperBuild.cmake, SuperBuild/External_GTest.cmake, SuperBuild/External_Gadgetron.cmake, version_config.cmake
Closes #19 and #50 
`find_package(GTest)` did not find the GTest on my VM, though
=> Uses GTest rather than googletest

version_config.cmake
=> self host fftw

version_config.cmake
=> uses origin/master rather than master

.travis.yml, SuperBuild/External_Boost.cmake, SuperBuild/External_Boost_configureboost.cmake, docker/Dockerfile
=> Boost build

CHANGES.md, version_config.cmake
release checklist https://github.com/CCPPETMR/SIRF/issues/178
=> preparation for tagging v1.1

env_ccppetmr.csh.in, env_ccppetmr.sh.in
=> prepend SIRF install dir to PATH env

SuperBuild/External_ACE.cmake
=> fixes missing ACE install step

version_config.cmake
=> set minimum Boost version to 1.64

.travis.yml
refer to https://github.com/CCPPETMR/SIRF/pull/201
closes #133
=> reinstall boost instead of upgrade

.travis.yml
Fixes issues with PRs failing due to not having stats access permissions
=> CI statistics fixes

.travis.yml
installs CMake 3.13.1
calls travis_terminate 1 in the whole block running cmake config and make (was only at make)
closes #174 (possibly)
=> fix various Travis issues (update CMake, fail on error, boost and ACE)

SuperBuild.cmake, SuperBuild/External_Gadgetron.cmake, SuperBuild/External_ISMRMRD.cmake, SuperBuild/External_ITK.cmake, SuperBuild/External_SIRF.cmake, SuperBuild/External_STIR.cmake
=> Add CMake options for testing sub-projects

SuperBuild/External_Boost.cmake, SuperBuild/External_Boost_configureboost.cmake, SuperBuild/External_GTest.cmake, SuperBuild/External_Gadgetron.cmake, SuperBuild/External_HDF5.cmake, SuperBuild/External_ISMRMRD.cmake, SuperBuild/External_ITK.cmake, SuperBuild/External_NiftyReg.cmake, SuperBuild/External_SIRF.cmake, SuperBuild/External_STIR.cmake, SuperBuild/External_glog.cmake, SuperBuild/External_petmr_rd_tools.cmake, SuperBuild/External_siemens_to_ismrmrd.cmake
=> uses STATUS mode in cmake message

SuperBuild/External_ITK.cmake
Disables build of ITK Review module (`Module_ITKReview`).
=> Do not build ITK with Review module

SuperBuild/External_NiftyReg.cmake
=> fix linking NiftyReg with OpenMP

CHANGES.md, CMakeLists.txt, README.md
=> require CMake 3.10

version_config.cmake
update niftyreg version to 1.5.63 (this will eventually solve https://github.com/CCPPETMR/SIRF/issues/352)
=> update niftyreg version

version_config.cmake
temporary fix for https://github.com/CCPPETMR/SIRF/issues/354
=> use older version of STIR until problem fixed

SuperBuild/External_Gadgetron.cmake
=> bugfix find blas

version_config.cmake
=> renamed PET rd tools

SuperBuild/External_STIR.cmake
=> fixed variable name default_STIR_BUILD_EXECUTABLE

docker/README.md
ported from wiki (https://github.com/CCPPETMR/SIRF/wiki/SIRF-SuperBuild-on-Docker)
=> docker: add full documentation

SuperBuild/External_CCPi-Framework.cmake, patches/cil-patch.py
Adds a patch script for the CCPi-Framework installation.
=> CCPi patch script

SuperBuild/External_STIR.cmake
=> BUG_FIX: Extern_STIR - Replace ! with NOT

.travis.yml, docker/Dockerfile, docker/docker-compose.devel.yml, docker/docker-compose.nix.yml, docker/docker-compose.srv-gpu.yml, docker/docker-compose.srv-multi.yml, docker/docker-compose.srv.yml, docker/docker-compose.yml, docker/sirf-compose-server-gpu
adds:
- `ccppetmr/sirf:core-gpu` image
- `ccppetmr/sirf:service-gpu` image
- `sirf-compose-server-gpu` helper script
Based off
- `nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04`
And option to base off any other image.
=> GPU docker support

.travis.yml
Addresses https://github.com/CCPPETMR/SIRF-SuperBuild/issues/292 as per https://github.com/CCPPETMR/SIRF/pull/470
=> attempt to fix travis OSX

.travis.yml
Travis CIL jobs currently failing so disable until fixed via PR.
=> temporarily disable cil

README.md
Fix mentioned typos and add location variable to instructions.
=> Update README.md (Fix issue #318)

SuperBuild/External_NIFTYREG.cmake
A clean version of PR #335 .
Resolves #349
=> Add possibility to set your own git tag and repo for NIFTYREG

SuperBuild/External_NIFTYREG.cmake
add `EP_ARGS_DIRS` variable (forgot to do it in  #337)
=> added ${${proj}_EP_ARGS_DIRS} in NIFTYREG

CMake/SetGitTagAndRepo.cmake, SuperBuild/External_Gadgetron.cmake, SuperBuild/External_NIFTYREG.cmake, SuperBuild/External_SIRF.cmake, SuperBuild/External_STIR.cmake
Resolves #336
I can add this too to PR #350 if that gets merged. 
However this still has the issue that @rijobro mentioned: In order to change the git checkout, you need to have the repo downloaded already, otherwise it will not work. I do not know how to fix that, I am open to suggestions.
=> Clean up conditional git CMAKE args

SuperBuild/External_JSON.cmake, SuperBuild/External_STIR.cmake, version_config.cmake
=> added JSON as external package

SuperBuild/External_STIR.cmake
Addresses part of https://github.com/SyneRBI/SIRF-SuperBuild/issues/374
=> option to disable STIR JSON support

SuperBuild/External_STIR.cmake
fixes https://github.com/SyneRBI/SIRF-SuperBuild/issues/382
=> need all options before adding dependencies

SuperBuild.cmake
fixes https://github.com/SyneRBI/SIRF-SuperBuild/issues/383
=> correct logic around building sirf and registration

SuperBuild/External_SWIG.cmake
=> check if default swig executable exists

.travis.yml, SuperBuild/External_ITK.cmake
- add new option `ITK_MINIMAL_LIBS` (default to `ON`) to build less of ITK
- allow use of option `ITK_EXTRA_CMAKE_ARGS`
fixes #210
=> changes to ITK building

SuperBuild/External_CCPi-Framework.cmake
adds test from CIL with BlockDataContainer and SIRF objects
=> add test_SIRF unittest

version_config.cmake
=> upgrade pet-rd-tools to v2.0.1

.travis.yml
- fixes https://github.com/SyneRBI/SyneRBI-admin/issues/1
=> fix docker pull rate limit

docker/README.md, docker/docker-compose.devel.yml, docker/sirf-compose, docker/sirf-compose-devel, docker/sirf-compose-devel-server, docker/sirf-compose-devel-server-gpu, docker/sirf-compose-devel-server-multi, docker/sirf-compose-server, docker/sirf-compose-server-gpu, docker/sirf-compose-server-multi
updated README and make it easier to run the devel image.
=> Small Docker additions

.mailmap, .zenodo.json, README.md
also update .mailmap
fixes #465
=> add zenodo info

docker/user_python-ubuntu.sh
=> switch default docker Python to miniconda3

SuperBuild/External_Gadgetron.cmake, patches/copy_file_if_not_exists.py
=> copy Gadgetron config file if not exists

.github/workflows/c-cpp.yml
using https://github.com/hendrikmuhs/ccache-action
see #514
=> add ccache to github action

.github/workflows/c-cpp.yml, docker/build_essential-ubuntu.sh, docker/build_gadgetron-ubuntu.sh
- less of boost 
- use gcc8
Both will decrease size and speed install up
=> Change docker dependencies

docker/user_python-ubuntu.sh
=> Fix user_python script

docker/Dockerfile
=> BUILD_pet_rd_tools=ON for Docker

docker/Dockerfile, docker/build_essential-ubuntu.sh, docker/download_data.sh, docker/service.sh
Does not download the SIRF-Exercises by default on first start. User needs to specify it.
=> docker: not download data automatically

README.md
Avoid a double redirect, as it is now
=> README Docker link

docker/user_service-ubuntu.sh
=> Docker use exercises requirements

SuperBuild/External_CCPi-Regularisation-Toolkit.cmake
added environment variable CIL_VERSION required at install otherwise the build fails
=> added environment variable CIL_VERSION required at install

docker/docker-compose.srv-gpu.yml
=> [docker] add BASE_IMAGE to GPU image

.travis.yml, docker/README.md, docker/entrypoint.sh, docker/service.sh
- Fixes #553 by not running the test (which isn't great)
- Addresses #555 by writing more diagnostics and combining `chgrp/chown` (but still slow)
- edit README (fixes #552)
=> some Docker fixes

docker/.dockerignore
=> correct .dockerignore file

CHANGES.md, docker/.dockerignore, docker/Dockerfile, docker/requirements.txt, docker/requirements_conda_forge.txt, docker/user_python-ubuntu.sh, docker/user_sirf-ubuntu.sh
=> 562 conda forge deps

docker/README.md
=> [ci skip] updated README

.travis.yml
=> docker on travis permisssions

version_config.cmake
=> bump SIRF_TAG

CHANGES.md, docker/DocForDevelopers.md, docker/Dockerfile, docker/README.md, docker/docker-compose.yml, docker/service.sh, docker/user_sirf-ubuntu.sh
See commit messages
Fixes #589 
Fixes #572 
but also some introduces a `NUM_PARALLEL_BUILDS` variable
=> Docker improvements

docker/README.md
- Moved Introduction to straight after TL;DR
- Outlined in a few relevant places how to re-build. (what about re-pull?)
- I found I needed to build using the convenience function, not just `docker-compose`, on Linux.
- Other minor edits
Please check for accuracy! I've tried hard to fully understand how it's all working here - but I didn't write these configurations and convenience wrappers.
=> Updated to Docker README

version_config.cmake
=> bump CIL tag

CMakeLists.txt
declare what behaviour we expect
=> declare behaviour with policy 0077

CHANGES.md, version_config.cmake
=> ISMRMRD 1.5.0

CHANGES.md, SuperBuild/External_Boost_configureboost.cmake, docker/build_gadgetron-ubuntu.sh
Installs Boost random or builds it for ISMRMRD 1.5.0
closes #636
=> Add Boost random

CHANGES.md, version_config.cmake
updates versions of JSON, Boost, ACE, Gtest
Closes #651
=> update JSON Boost ACE GTest versions

.github/workflows/c-cpp.yml, docker/build_gadgetron-ubuntu.sh, version_config.cmake
=> Install OpenBLAS and bump CIL version

CHANGES.md, docker/build_essential-ubuntu.sh, version_config.cmake
=> Set Boost to 1.62 and CMake to 3.16.2

docker/user_sirf-ubuntu.sh
=> uses := operator for bash parameter expansion

SuperBuild/External_CIL-ASTRA.cmake
=> change the CIL-ASTRA install command

docker/build_gadgetron-ubuntu.sh
=> adds -yq to apt install command

CHANGES.md, SuperBuild.cmake
=> remove PYVER variable, support only Python 3

.github/workflows/c-cpp.yml, docker/.bashrc, docker/Dockerfile, docker/user_python-ubuntu.sh, jupyterhub/README.md
=> Fix python dest bashrc

CHANGES.md, VirtualBox/scripts/UPDATE.sh
=> build full CIL

VirtualBox/scripts/UPDATE.sh
=> install astra

docker/user_python-ubuntu.sh
=> invert pip and conda steps

version_config.cmake
=> use STIR release_5.0

docker/build_system-ubuntu.sh
=> install software-properties-common (needed for add-apt-repository)

docker/Dockerfile, docker/update_nvidia_keys.sh
=> install gnupg in the base ubuntu:18.04 image

VirtualBox/scripts/bootstrap_ubuntu.sh
=> remove non existing branch

docker/requirements_conda_forge.txt
Equivalent to https://github.com/SyneRBI/SIRF-SuperBuild/pull/752 without all the GHA to test docker.
=> Fix travis build

docker/requirements.txt
=> docker: use most recent numba anyway

.github/workflows/c-cpp.yml, CHANGES.md, docker/Dockerfile, docker/README.md, docker/build_essential-ubuntu.sh, docker/docker-compose.srv-gpu.yml, docker/docker-compose.yml, docker/update_nvidia_keys.sh, docker/user_sirf-ubuntu.sh
=> Move docker images to ubuntu 20.04

README.md, jupyterhub/README.md
updates the documentation for jupyterhub
=> [ci skip] updated jupyterhub readme

.travis.yml
- clean-up
- remove stats functionality as Travis complains
But i cannot test it as it needs to be on `master`, so I'll merge
=> [TRAVIS] removed most things except docker

CHANGES.md, VirtualBox/Using_VM_as_server.md, VirtualBox/documentation/Getting-started-with-SIRF.md, VirtualBox/scripts/configure_jupyter.sh, docker/service.multi.sh, docker/service.sh
=> switch to jupyter lab

CHANGES.md, VirtualBox/scripts/bootstrap_ubuntu.sh, VirtualBox/scripts/first_run.sh, VirtualBox/vagrant/README.md, VirtualBox/vagrant/Vagrantfile
@paskino, see commit messages below and diff.
It works for me, so I'll merge this soon
=> VM improvements

version_config.cmake
=> Update Gadgetron tag

.github/workflows/GHA_increase_disk_space.sh, .github/workflows/c-cpp.yml, .github/workflows/docker_build.yml, CHANGES.md, docker/service.sh
=> [docker] remove obsolete copying of gadgetron.xml

CHANGES.md, SuperBuild/External_CIL.cmake, version_config.cmake
This reinstates the tests for the SIRF/CIL integration present in CIL.
=> Add SIRF/CIL integration tests

docker/Dockerfile
=> ci: fix docker builds

VirtualBox/INSTALL.md, VirtualBox/README.md, VirtualBox/documentation/Basic-usage.md, VirtualBox/documentation/README.md, VirtualBox/documentation/Using-VM-as-a-Gadgetron-server.md, VirtualBox/vagrant/README.md
Try to remove some circularity in the doc, and update it
=> Update/improve the VM documentation

CHANGES.md, docker/requirements.txt, version_config.cmake
See the diff for what the new versions are
Fixes #851
=> update versions of many dependencies

.github/workflows/docker.yml
=> CI: fix docker tags

version_config.cmake
=> Use our own fork for Date to fix the gitattributes problem

.github/workflows/c-cpp.yml, .github/workflows/docker.yml, docker/build_system-ubuntu.sh, docker/raw-ubuntu.sh
`c-cpp.yml` (`native`) and `docker.yml` workflow updates
- shorter job names
- bump actions (fixes #860)
- fix `tmate` debugging
- cache `pip`
- `ccache` fallback keys
- better debug artefact name
- fix docker release auth
- use https://github.com/jlumbroso/free-disk-space action
- fix silent failures
=> workflow tidy

SuperBuild/External_STIR.cmake
=> don't add dependent projects if USE_SYSTEM_STIR=ON

VirtualBox/documentation/Basic-usage.md, VirtualBox/scripts/UPDATE.sh, VirtualBox/scripts/UPDATE_functions.sh
=> VM update script updates

CHANGES.md, VirtualBox/scripts/UPDATE_functions.sh
allow setting DEVEL_BUILD=ON and skipping the build. The latter is mostly useful when creating a VM.
=> [VB] add extra options for developers

VirtualBox/requirements-jupyter.txt, VirtualBox/scripts/INSTALL_python_packages.sh, VirtualBox/scripts/bootstrap_ubuntu.sh, VirtualBox/vagrant/README.md
=> final (?) fixes for VM building

.github/workflows/docker.yml, docker-compose.yml, docker/README.md, docker/compose.sh, docker/devel/shared.txt, docker/docker-compose.devel-gpu.yml, docker/docker-compose.devel.yml, docker/docker-compose.gpu.yml
- fix `localhost` URL (fixes #889)
- fix `-gpu` suffix
- document tags (fixes #890)
+ drop `:jupyter` tag (just use `:latest`) [5168369](https://github.com/SyneRBI/SIRF-SuperBuild/pull/891/commits/5168369b87bd988f3d7b5ce43849b40eb9200f94) - maybe revert?
=> docker docs

CHANGES.md
=> update CHANGES.md for 3.6.0 regarding docker

docker/README.md
following https://github.com/SyneRBI/SIRF-SuperBuild/pull/893#discussion_r1535343773
=> docs: remove unpushed docker `devel`

.github/workflows/test_cil.sh
=> Update test_cil.sh to go back to normal CIL-version mechanism

CHANGES.md, version_config.cmake
=> bump Armadillo

version_config.cmake
as per #920
@casperdcl @evgueni-ovtchinnikov please merge if ok.
=> Use SIRF-Contribs tag 3.8.0 unless DEVEL_BUILD=ON

VirtualBox/INSTALL.md
=> Update VM INSTALL instructions to point to most recent VM on Zenodo
